version: "3.9"

services:
    postgres:
        image: postgres:16
        container_name: db-bank-project
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: db_bank_project
            POSTGRES_USER: db_bank_user
            POSTGRES_PASSWORD: app_password_1234
        volumes:
            - pgdata:/var/lib/postgresql/data

volumes:
    pgdata:
# postgresql://db_bank_user:app_password_1234@localhost:5432/db_bank_project
