version: "3.9"

services:
    postgres:
        image: postgres:16
        container_name: db-bank-project
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: db-bank-project
            POSTGRES_USER: db-bank-simple-user
            POSTGRES_PASSWORD: app_password_1234
        volumes:
            - pgdata:/var/lib/postgresql/data

volumes:
    pgdata:
# postgresql://app_user:app_password@localhost:5432/app_db
